# Generated by Django 5.2.15 on 2026-06-17 10:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Organization ID must contain only alphanumeric characters and hyphens.', regex='^[a-zA-Z0-9\\-]+$')])),
                ('name', models.CharField(max_length=255)),
                ('company_creation_policy', models.CharField(choices=[('ORG_ADMIN', 'Centralized (Org Admin Only)'), ('BRANCH_ADMIN', 'Decentralized (Branch Admins)')], default='ORG_ADMIN', max_length=20)),
                ('item_creation_policy', models.CharField(choices=[('ORG_ADMIN', 'Centralized (Org Admin Only)'), ('BRANCH_ADMIN', 'Decentralized (Branch Admins)')], default='ORG_ADMIN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
