# Generated by Django 5.2.15 on 2026-06-17 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Organization ID must be at least 5 characters long.'), django.core.validators.RegexValidator(message='Organization ID must contain only letters and numbers without special characters.', regex='^[a-zA-Z0-9]+$'), django.core.validators.RegexValidator(message='Organization ID must contain at least one letter.', regex='[a-zA-Z]'), django.core.validators.RegexValidator(message='Organization ID must contain at least one number.', regex='[0-9]')]),
        ),
    ]
