# Generated by Django 5.2.15 on 2026-06-20 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_type', models.CharField(max_length=50)),
                ('next_val', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'sequence_type'), name='unique_org_sequence_type'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'sequence_type'), name='unique_branch_sequence_type')],
            },
        ),
    ]
