# Generated by Django 5.2.15 on 2026-07-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branchsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='company_creation_policy',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='item_creation_policy',
        ),
    ]
