# Generated by Django 5.2.15 on 2026-06-17 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'Organization Admin'), ('ORG_USER', 'Organization User'), ('BRANCH_ADMIN', 'Branch Admin'), ('USER', 'Branch User'), ('KPO', 'KPO (Seller)')], default='KPO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['ORG_ADMIN', 'ORG_USER'])), fields=('organization', 'username'), name='unique_org_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['BRANCH_ADMIN', 'USER', 'KPO'])), fields=('branch', 'username'), name='unique_branch_username'),
        ),
    ]
