# Generated by Django 5.2.15 on 2026-06-19 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('organizations', '0002_alter_organization_org_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('pack', models.IntegerField(blank=True, null=True)),
                ('grammage', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sales_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('federal_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_slab_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_slab_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='organizations.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='companies.company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_categories', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_categories', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemApprovalQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('pack', models.IntegerField(blank=True, null=True)),
                ('grammage', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sales_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('federal_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_slab_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_slab_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='organizations.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='companies.company')),
                ('created_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='items.itemcategory')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.itemcategory'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_category_name'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_category_name'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'code'), name='unique_org_category_code'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'code'), name='unique_branch_category_code'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_item_name'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_item_name'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'code'), name='unique_org_item_code'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'code'), name='unique_branch_item_code'),
        ),
    ]
