# Generated by Django 5.2.15 on 2026-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
