# Generated by Django 5.2.15 on 2026-06-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_current_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemApprovalQueue',
        ),
    ]
