# Generated by Django 5.2.15 on 2026-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_delete_itemapprovalqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
