# Generated by Django 5.2.15 on 2026-07-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_policies_branch_m2m'),
        ('items', '0005_item_damaged_stock'),
        ('organizations', '0004_remove_policies_branch_m2m'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_org_item_name',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_branch_item_name',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_org_item_code',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_branch_item_code',
        ),
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='unique_org_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='unique_branch_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='unique_org_category_code',
        ),
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='unique_branch_category_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='branch',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_item_name'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_org_item_code'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_category_name'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_org_category_code'),
        ),
    ]
