# Generated by Django 5.2.15 on 2026-06-19 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_company_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_company_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'code'), name='unique_org_company_code'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'code'), name='unique_branch_company_code')],
            },
        ),
    ]
