# Generated by Django 5.2.15 on 2026-07-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_version'),
        ('organizations', '0004_remove_policies_branch_m2m'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_org_company_name',
        ),
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_branch_company_name',
        ),
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_org_company_code',
        ),
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_branch_company_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='branch',
        ),
        migrations.AddField(
            model_name='company',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='companies', to='organizations.branch'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_company_name'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_org_company_code'),
        ),
    ]
