# Generated by Django 5.2.15 on 2026-06-19 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_account_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_account_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'code'), name='unique_org_account_code'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'code'), name='unique_branch_account_code')],
            },
        ),
        migrations.CreateModel(
            name='OrderBooker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_bookers', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_bookers', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_orderbooker_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_orderbooker_name')],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_party_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_party_name')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_accounts', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_accounts', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_paymentaccount_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_paymentaccount_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'code'), name='unique_org_paymentaccount_code'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'code'), name='unique_branch_paymentaccount_code')],
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesmen', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesmen', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Salesmen',
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_salesman_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_salesman_name')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'name'), name='unique_org_supplier_name'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='unique_branch_supplier_name')],
            },
        ),
    ]
