# Generated by Django 5.2.15 on 2026-06-19 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_payment_account_types(apps, schema_editor):
    PaymentAccountType = apps.get_model('registers', 'PaymentAccountType')
    PaymentAccountType.objects.get_or_create(code='CASH', defaults={'name': 'Cash'})
    PaymentAccountType.objects.get_or_create(code='BANK', defaults={'name': 'Bank'})
    PaymentAccountType.objects.get_or_create(code='CHEQUE', defaults={'name': 'Cheque'})


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccountType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_payment_account_types, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='accountopening',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_accounts', to='registers.paymentaccounttype'),
        ),
    ]
