# Generated by Django 5.2.15 on 2026-06-19 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('items', '0002_item_current_stock'),
        ('organizations', '0002_alter_organization_org_id'),
        ('registers', '0002_paymentaccounttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='party',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='party',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='is_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='ntn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_code', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('s_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('freight', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adv_income_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='registers.accountopening')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='companies.company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='organizations.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='registers.party')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carton', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('to_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('to_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('s_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('s_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='registers.purchaseinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_items', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_code', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ntn', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_days', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='registers.accountopening')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='companies.company')),
                ('order_booker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='registers.orderbooker')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='organizations.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='registers.party')),
                ('payment_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='registers.paymentaccount')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='registers.salesman')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bal_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('carton', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('s_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('f_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('to_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('to_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='registers.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_items', to='items.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'purchase_code'), name='unique_org_purchase_invoice_code'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'purchase_code'), name='unique_branch_purchase_invoice_code'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'sale_code'), name='unique_org_sales_invoice_code'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'sale_code'), name='unique_branch_sales_invoice_code'),
        ),
    ]
