# Generated by Django 5.2.15 on 2026-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_party_balance_amount_party_credit_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='credit_days',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ntn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
