# Generated by Django 5.2.15 on 2026-06-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_purchaseinvoice_payment_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_acc',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_acc',
        ),
        migrations.DeleteModel(
            name='PaymentAccountType',
        ),
        migrations.DeleteModel(
            name='PaymentAccount',
        ),
    ]
