# Generated by Django 5.2.15 on 2026-06-20 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_version'),
        ('items', '0005_item_damaged_stock'),
        ('organizations', '0003_branchsequence'),
        ('registers', '0009_damagereturn_journalentry_damage_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReceiving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('damage_receiving_code', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('s_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ntn', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_days', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_receivings', to='registers.accountopening')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_receivings', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_receivings', to='companies.company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_receivings', to='organizations.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_receivings', to='registers.party')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_receivings', to='registers.salesman')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='damage_receiving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='registers.damagereceiving'),
        ),
        migrations.CreateModel(
            name='DamageReceivingLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_code', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_units', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('s_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('s_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('damage_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='registers.damagereceiving')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_receiving_items', to='items.item')),
            ],
        ),
        migrations.AddConstraint(
            model_name='damagereceiving',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'damage_receiving_code'), name='unique_org_damage_receiving_code'),
        ),
        migrations.AddConstraint(
            model_name='damagereceiving',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'damage_receiving_code'), name='unique_branch_damage_receiving_code'),
        ),
    ]
