# Generated by Django 5.2.15 on 2026-07-17 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_policies_branch_m2m'),
        ('items', '0006_remove_policies_branch_m2m'),
        ('organizations', '0004_remove_policies_branch_m2m'),
        ('registers', '0010_damagereceiving_journalentry_damage_receiving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='return_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('damage', 'Damage')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_return_code', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('return_type', models.CharField(choices=[('normal', 'Normal'), ('damage', 'Damage')], default='normal', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('s_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ntn', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_days', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='registers.accountopening')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='companies.company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='organizations.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='registers.party')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='registers.salesman')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_code', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_units', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('s_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('s_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='items.item')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='registers.salesreturn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization', 'sales_return_code'), name='unique_org_sales_return_code'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'sales_return_code'), name='unique_branch_sales_return_code'),
        ),
    ]
