# Generated by Django 5.2.15 on 2026-07-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_purchasereturn_return_type_salesreturn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereceivinglineitem',
            name='damage_receiving',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='damage_receiving',
        ),
        migrations.RemoveField(
            model_name='damagereceivinglineitem',
            name='item',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='registers.salesreturn'),
        ),
        migrations.DeleteModel(
            name='DamageReceiving',
        ),
        migrations.DeleteModel(
            name='DamageReceivingLineItem',
        ),
    ]
