# Generated by Django 5.2.15 on 2026-07-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_remove_damagereceivinglineitem_damage_receiving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnlineitem',
            name='carton',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
