# Generated by Django 5.2.15 on 2026-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_policies_branch_m2m'),
        ('organizations', '0004_remove_policies_branch_m2m'),
        ('registers', '0013_salesreturnlineitem_carton'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'status'], name='registers_p_company_11baa2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'return_type'], name='registers_p_company_d92523_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', '-created_at'], name='registers_p_company_7d35ee_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'status'], name='registers_s_company_2c8f51_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'return_type'], name='registers_s_company_eb9b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', '-created_at'], name='registers_s_company_10ca6b_idx'),
        ),
    ]
